### ISSUE TITLE
How to delete existing accounts

### ISSUE THREAD

**Issue by thekingofcity** [shadowsocks/shadowsocks-hub#3]
Everything expect requests have delete options, however clicking these prompt reference error.
So I turn to requests, hoping to find a delete option, but I can't.
**How can I delete existing accounts?**

**Comment by Eggham** [comment]
@thekingofcity Good question! At the moment, an account cannot be deleted once traffic data for the account is stored in the database (even the traffic is zero).

Perhaps I will need to refactor the api so that deleting an account means deleting all the traffic belonging to the account and then deleting the account.

**Comment by thekingofcity** [comment]
Oh I see, waiting for your new commits. :)
For now, it seems I have no choice but to drop the database and recreate it again.

**Comment by Eggham** [comment]
Done with 3efa20f.
